#!/usr/bin/bash
OLD="$(pwd)"
_SRC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

mkdir -p libnetsurf
cd libnetsurf

wget \
	http://download.netsurf-browser.org/libs/releases/buildsystem-1.10.tar.gz \
	http://download.netsurf-browser.org/libs/releases/libparserutils-0.2.5-src.tar.gz \
	http://download.netsurf-browser.org/libs/releases/libwapcaplet-0.4.3-src.tar.gz \
	http://download.netsurf-browser.org/libs/releases/libhubbub-0.3.8-src.tar.gz \
	http://download.netsurf-browser.org/libs/releases/libcss-0.9.2-src.tar.gz \
	http://download.netsurf-browser.org/libs/releases/libdom-0.4.2-src.tar.gz 

tar -xf *.tar.gz
export CFLAGS="-Wno-error"

#PREFIX=/opt/elinks
ASLIBSTATIC="-j1 Q= LIBDIR=lib COMPONENT_TYPE=lib-static"
sudo sh -c "\
make -C buildsystem-1.10 install
make -C libparserutils-0.2.5 install $ASLIBSTATIC
make -C libwapcaplet-0.4.3 install $ASLIBSTATIC
make -C libhubbub-0.3.8 install $ASLIBSTATIC
make -C libcss-0.9.2 install $ASLIBSTATIC
make -C libdom-0.4.2 install $ASLIBSTATIC
"

cd "${OLD}"
unset _SRC OLD PREFIX ASLIBSTATIC
