#!/usr/bin/bash
OLD="$(pwd)"
_SRC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "${_SRC}/elinks"
git pull #|| exit 1
git log ORIG_HEAD..
rm -rf build

meson setup $(< ../elinks.mf) build --prefix=/usr \
|| { ${PAGER:-pager} build/meson-logs/meson-log.txt; exit 2; }
meson compile -j $((($(nproc) - 1))) -C build || exit 3

rm -rf "${_SRC}/AppDir"
DESTDIR="${_SRC}/AppDir" meson install -C build/   || exit 5

cd ..

mkdir -p AppDir/etc/
cp -r elinks-odds/config AppDir/etc/elinks

if [ ! -d linuxdeploy ] ; then
    mkdir linuxdeploy
    cd linuxdeploy
    wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
    wget https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/continuous/linuxdeploy-plugin-appimage-x86_64.AppImage
    chmod +x linuxdeploy-x86_64.AppImage
    chmod +x linuxdeploy-plugin-appimage-x86_64.AppImage
    cd ..
fi

linuxdeploy/linuxdeploy-x86_64.AppImage --appdir AppDir \
    -e AppDir/usr/bin/elinks \
    -d elinks-odds/elinks.desktop \
    -i elinks-odds/lynx.png

rm AppDir/AppRun
cp elinks-odds/AppRun AppDir/AppRun

linuxdeploy/linuxdeploy-plugin-appimage-x86_64.AppImage --appdir AppDir

cd "$OLD"
unset _SRC OLD
