#!/usr/bin/bash
OLD="$(pwd)"
_SRC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd ${_SRC}/elinks
git pull #|| exit 1
git log ORIG_HEAD..
rm -rf build

meson setup $(< ../elinks.mf) build \
|| { ${PAGER:-pager} build/meson-logs/meson-log.txt; exit 2; }
meson compile -j $((($(nproc) - 1))) -C build || exit 3

if [ -z "$NOINSTALL" ] ; then
#strip build/src/elinks || exit 4
sudo meson install -C build/   || exit 5
#sudo upx /usr/local/bin/elinks || exit 6
fi

cd "$OLD"
unset _SRC OLD
