#!/usr/bin/bash
_OLD="$(pwd)"
_SRC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ARCH="${ARCH:-$(gcc -dumpmachine)}"

git_log() {
    if [ -n "${GIT_LOG_SHOW}" ]
    then git log ORIG_HEAD..
    fi
}

meson_setup() {
    meson setup $(< "${_SRC}/meson-flags/$1") $MESON_PATHS build \
    -Dcmake_prefix_path="${_SRC}/AppDir/usr:${_SRC}/AppDir" \
    -Dpkg_config_path="${_SRC}/AppDir/usr/lib/${ARCH}/pkgconfig:${_SRC}/AppDir/usr/lib/pkgconfig:${_SRC}/AppDir/lib/pkgconfig" \
    -Dcpp_args="-I${_SRC}/AppDir/usr/include/quickjs-ng -I${_SRC}/AppDir/usr/include -I${_SRC}/AppDir/include" \
    -Dc_args="-I${_SRC}/AppDir/usr/include/quickjs-ng -I${_SRC}/AppDir/usr/include -I${_SRC}/AppDir/include" \
    -Dcpp_link_args="-L${_SRC}/AppDir/usr/lib/${ARCH} -L${_SRC}/AppDir/usr/lib" \
    -Dc_link_args="-L${_SRC}/AppDir/usr/lib/${ARCH} -L${_SRC}/AppDir/usr/lib" \
    --prefix=/usr \
    || { ${PAGER:-pager} build/meson-logs/meson-log.txt; exit $2; }
}

cd "${_SRC}"
echo "--- $0 ($(date))"
rm -rf AppDir
mkdir -p repos
./setup-libnetsurf

cd repos

if [ ! -d linuxdeploy ] ; then
    mkdir linuxdeploy
    cd linuxdeploy
    wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
    wget https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/continuous/linuxdeploy-plugin-appimage-x86_64.AppImage
    chmod +x linuxdeploy-x86_64.AppImage
    chmod +x linuxdeploy-plugin-appimage-x86_64.AppImage
    cd ..
fi

if [ ! -d quickjs ]
then
    git clone https://github.com/quickjs-ng/quickjs.git
    cd quickjs
else 
    cd quickjs
    git pull
    git_log
fi

rm -rf build

meson_setup quickjs 11
meson compile -j $((($(nproc) - 1))) -C build || exit 12

DESTDIR="${_SRC}/AppDir" meson install -C build/ || exit 13

cd ..

if [ ! -d elinks ]
then 
    git clone https://github.com/rkd77/elinks.git
    cd elinks
else 
    cd elinks
    git pull
    git_log
fi

rm -rf build

meson_setup elinks 21
meson compile -j $((($(nproc) - 1))) -C build || exit 22

DESTDIR="${_SRC}/AppDir" meson install -C build/ || exit 23

cd "${_SRC}"

cp -r odds/etc AppDir/etc

repos/linuxdeploy/linuxdeploy-x86_64.AppImage --appdir AppDir \
    -e AppDir/usr/bin/elinks \
    -d odds/elinks.desktop \
    -i odds/kruciai.png

rm AppDir/AppRun
cp odds/AppRun AppDir/AppRun

repos/linuxdeploy/linuxdeploy-plugin-appimage-x86_64.AppImage --appdir AppDir

cd "${_OLD}"
unset _SRC _OLD
