#!/usr/bin/bash
OLD="$(pwd)"
_SRC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "${_SRC}"

if [ ! -d "repos/libnetsurf" ]
then
mkdir -p repos/libnetsurf
cd repos/libnetsurf

for i in buildsystem-1.10 libparserutils-0.2.5-src libwapcaplet-0.4.3-src libhubbub-0.3.8-src libcss-0.9.2-src libdom-0.4.2-src 
do 
	wget http://download.netsurf-browser.org/libs/releases/$i.tar.gz
	tar -xf $i.tar.gz
done

export CFLAGS="-Wno-error"

export PREFIX=../AppDir
ASLIBSTATIC="-j1 Q= LIBDIR=lib COMPONENT_TYPE=lib-static"

make -C buildsystem-1.10 install
make -C libparserutils-0.2.5 install $ASLIBSTATIC
make -C libwapcaplet-0.4.3 install $ASLIBSTATIC
make -C libhubbub-0.3.8 install $ASLIBSTATIC
make -C libcss-0.9.2 install $ASLIBSTATIC
make -C libdom-0.4.2 install $ASLIBSTATIC

cd "${OLD}"
else cd repos/libnetsurf
fi

unset _SRC OLD PREFIX ASLIBSTATIC PREFIX CFLAGS
