#!/usr/bin/env bash

# AppImage Root or Main-executable
export AIR="$(dirname "$(readlink -f "${0}")")"
export AIM="${AIM:-elinks}"
OWD="$(pwd)"
OLD_PATH="${PATH}"
OLD_MANPATH="${MANPATH}"

# Touch config
if [ ! -d "$HOME/.config/elinks" ]; then
    cp -r "$AIR/etc/elinks" "$HOME/.config/elinks"
fi

# Execute something
cd "$AIR"
export PATH="${AIR}/usr/bin:${PATH}"
#export TEXTDOMAINDIR="${AIR}/usr/share/locale${TEXTDOMAINDIR:+:${TEXTDOMAINDIR}}"
#export XDG_DATA_DIRS="${AIR}/usr/share:${XDG_DATA_DIRS:-${HOME}/.local/share:/usr/local/share:/usr/share}"
export MANPATH="${AIR}/usr/share/man${MANPATH:+:${MANPATH}}"

if [ "$1" == "--save-cwd" ]
then
    cd "OWD"
    shift
fi

case $1 in
    help)
    echo "using: this.AppImage [ --save-cwd ] [ COMMAND ] [ ARGS ]

    commands:       description:
    sh, shell       runs shell in appimage root (\$AIR)
    qjs             runs quickjs' repl
    help            display this help page
    man [ PAGE ]    display manpage

    if command is not found, then runs ${AIM}
    "
    ;;

    sh|shell)
    shift
    ${SHELL:=bash} "$@"
    ;;

    qjs)
    shift
    qjs "$@"
    ;;

    man)
    shift
    PAGE=${1:-$AIM}
    shift
    man "$@" $PAGE
    ;;

    *) $AIM "$@" ;;
esac

export PATH="${OLD_PATH}"
export MANPATH="${OLD_MANPATH}"
cd "${OWD}"

# Delete local variablle
unset AIR AIM OWD OLD_PATH OLD_MANPATH
