#!/usr/bin/env bash

# AppImage Root
AIR="$(dirname "$(readlink -f "${0}")")"

# Touch config
if [ ! -d "$HOME/.config/elinks" ]; then
    cp -r "$AIR/etc/elinks" "$HOME/.config/elinks"
fi

# Execute app
exec "$AIR/usr/bin/elinks" "$@"

# Delete local variablle
unset AIR